const {ccclass, property} = cc._decorator;

@ccclass
export default class MessageRoutingManager {
    // ===================== 单例核心 - 完全对齐原JS =====================
    private static _instance: MessageRoutingManager = null!;
    public static instance(): MessageRoutingManager {
        if (!this._instance) {
            this._instance = new MessageRoutingManager();
            this._instance.initMessageRoutingManager();
        }
        return this._instance;
    }

    // ===================== 静态事件名常量 - 原JS所有事件名完整保留，一个不漏 =====================
    public static readonly MSG = {
        BINGO_CELL_CLICK: "BINGO_CELL_CLICK",
        BINGO_CELL_EFFECT: "BINGO_CELL_EFFECT",
        CHECK_CHRISTMAS_BOX: "CHECK_CHRISTMAS_BOX",
        CHAGE_BOX_AMOUNT: "CHANGE_BOX_AMOUNT",
        PROMOTION_BANNER: "PROMOTION_BANNER",
        PROMOTION_CLOSE: "PROMOTION_CLOSE",
        MOVE_ASTROROLLER: "MOVE_ASTROROLLER",
        ADDSTARTINMOVEMASTROPOPUP: "ADDSTARTINMOVEMASTROPOPUP",
        ADDASTROMOVEPOPUP: "ADDASTROMOVEPOPUP",
        CALLSHOPMAJORMOVEPOPUP: "CALLSHOPMAJORMOVEPOPUP",
        LOBBY_NEXT_STEP: "LOBBYNEXTSTAP",
        REFRESHSHOPLIST: "REFRESHSHOPLIST",
        TUTORIAL_END: "TUTORIAL_END",
        iosMVP_OFFER_START: "iosMVP_OFFER_START",
        SPIN_SLOT: "SPIN_SLOT",
        CLOSE_PAYTABLE_BUTTON: "CLOSE_PAYTABLE_BUTTON",
        MISSION_UPDATE: "MISSION_UPDATE",
        MISSION_COMPLETE: "MISSION_COMPLETE",
        START_CHANGE_LABEL: "START_CHANGE_LABEL",
        STOP_CHANGE_LABEL: "STOP_CHANGE_LABEL",
        CHANGE_MINIGAME: "CHANGE_MINIGAME",
        JUMPSTATER: "JUMPSTATER",
        WILDDEAL_START: "WILDDEAL_START",
        BINGOTOOLTIP: "BINGOTOOLTIP",
        ALLINPOPUP_START: "ALLINPOPUP_START",
        ALL_IN_POPUP_END: "ALLINPOPUP_END",
        ADDGIFTBALLOON: "ADDFIGTBALLOON",
        RESERVEDONBALLOON: "RESERVEDONBALLOON",
        UPDATE_SERVICE_INTRODUCE_COIN: "UPDATE_SERVICEINTRODUCECOIN",
        BLOCK_EVENT_SERVICEINTRODUCECOIN: "BLOCK_EVENT_SERVICEINTRODUCECOIN",
        END_NEW_USER_MISSION_PROMOTION: "ENDUSERMISSIONPROMOTION",
        ADD_NEW_USER_MISSION_COMPLETE: "ADDNEWUSERMISSIONCOMPLETE",
        GAVE_WELCOME_BONUS: "GAVEWELCOMEBONUS",
        CHANGE_USERLEVEL: "CHANGE_USERLEVEL",
        RESEVEDACTIVEHEROTOOLTIP: "RESEVEDACTIVEHEROTOOLTIP",
        OPENINGAMEMISSIONTOOLTIP: "OPENINGAMEMISSIONTOOLTIP",
        OPENINGAMEMISSIONTOOLTIP_ADD: "OPENINGAMEMISSIONTOOLTIP_ADD",
        TOURNEY_RESERVE_NEWGAME: "TOURNEY_RESERVE_NEWGAME",
        TOURNEY_START_NEWGAME: "TOURNEY_START_NEWGAME",
        TOURNEY_REFRESH_INFO: "TOURNEY_REFRESH_INFO",
        BINGOBALL_PURCHASE: "BINGOBALL_PURCHASE",
        RESET_START_POPUP: "RESET_STARTPOPUP",
        START_SEASONENDOFFER: "STARTSEASONENDOFFER",
        UPDATE_CORE: "UPDATE_CORE",
        UPDATE_SQUADSTATE: "UPDATE_SQUADSTATE",
        CHANGE_ACTIVE_HERO: "CHANGE_ACTIVE_HERO",
        SPIN_COUNT_UPDATE: "SPIN_COUNT_UPDATE",
        SET_LANGUAGE: "SET_LANGUAGE",
        CHANGE_FIRST_PRODUCT: "CHANGE_FIRST_PRODUCT",
        UPDATE_TUTORIAL: "UPDATE_TUTORIAL",
        UPDATE_SUITE_LEAGUE: "UPDATE_SUITE_LEAGUE",
        UPDATE_INGAME_SUITE_LEAGUE: "UPDATE_INGAME_SUITE_LEAGUE",
        CHANGE_TAB_INBOXANDFRIENDS: "CHANGE_TAB_INBOXANDFRIENDS",
        MOVE_TO_SLOT: "MOVE_TO_SLOT",
        CLOSE_RECENTLYPLAYED: "CLOSE_RECENTLYPLAYED",
        BINGO_GAME_START: "BINGO_GAME_START",
        REELQUEST_ALREADY_TARGETGAME: "REELQUEST_ALREADY_TARGETGAME",
        REFRESH_LOBBY_UI: "REFRESH_LOBBYSCENE_UI",
        REFRESH_INBOX_UI: "REFRESH_INBOX_UI",
        REFRESH_INGAME_UI: "REFRESH_INGAMESCENE_UI",
        OPEN_TOOLTIP: "OPEN_TOOLTIP_UI",
        REFRESH_CENTURION_CLIQUE: "REFRESH_CENTURION_CLIQUE",
        INGAME_LEVEL_UP_PASS_ICON_BOOST_EFFECT: "INGAME_LEVEL_UP_PASS_ICON_BOOST_EFFECT",
        OPEN_POWERGEM_PROMOTION: "OPEN_POWERGEM_PROMOTION",
        REFRESH_STAMP_TAG: "RESET_STAMP_TAG",
        REWARD_CENTER_CHANGE_VIEW: "REWARD_CENTER_CHANGE_VIEW",
        REWARD_CENTER_UPDATE_VIEW: "REWARD_CENTER_UPDATE_VIEW",
        REWARD_CENTER_SHOW_SENT_POPUP: "REWARD_CENTER_SHOW_SENT_POPUP",
        REWARD_CENTER_UPDATE_INBOX: "REWARD_CENTER_UPDATE_INBOX",
        REWARD_CENTER_REMOVE_INBOX: "REWARD_CENTER_REMOVE_INBOX",
        REWARD_CENTER_UPDATE_UI_TIME_BONUS: "REWARD_CENTER_UPDATE_UI_TIME_BONUS",
        REWARD_CENTER_UPDATE_UI_SPIN_BOOSTER: "REWARD_CENTER_UPDATE_UI_SPIN_BOOSTER",
        REWARD_CENTER_BLOCK_TOUCH: "REWARD_CENTER_BLOCK_TOUCH",
        REWARD_CENTER_CLOSE_DISABLE: "REWARD_CENTER_CLOSE_DISABLE",
        REFRESH_SUPERSIZE_IT_COUNT: "REFRESH_SUPERSIZE_IT_COUNT",
        REFRESH_SUPERSIZE_IT_COUNT_SELF: "REFRESH_SUPERSIZE_IT_COUNT_SELF",
        REFRESH_SUPERSIZE_IT_END: "REFRESH_SUPERSIZE_IT_END",
        APPEND_SUPERSIZE_IT_NOTIFY: "APPEND_SUPERSIZE_IT_NOTIFY",
        SUPERSIZE_LOBBY_TAG_UPDATE: "SUPERSIZE_LOBBY_TAG_UPDATE",
        REFRESH_SPIN_2_WIN_COUNT: "REFRESH_SPIN_2_WIN_COUNT",
        HYPER_BOUNTY_OPEN_TOOLTIP: "HYPER_BOUNTY_OPEN_TOOLTIP",
        HYPER_BOUNTY_OPEN_PURCHASE_POPUP: "HYPER_BOUNTY_OPEN_PURCHASE_POPUP",
        HYPER_BOUNTY_MISSION_UPDATE: "HYPER_BOUNTY_MISSION_UPDATE",
        HYPER_BOUNTY_SPIN_COUNT_UPDATE: "HYPER_BOUNTY_SPIN_COUNT_UPDATE",
        LOBBY_MOVE_SCROLL_TO_INDEX: "MOVE_LOBBY_SCROLL_TO_INDEX",
        LOBBY_MOVE_SCROLL_TO_OFFSET: "MOVE_LOBBY_SCROLL_TO_OFFSET",
        LOBBY_MOVE_SCROLL_TO_BANNER: "MOVE_LOBBY_SCROLL_TO_BANNER",
        LOBBY_MOVE_SCROLL_TO_SLOT: "MOVE_LOBBY_SCROLL_TO_SLOT",
        LOBBY_REFRESH_ALL_BANNER_ITEM: "REFRESH_LOBBY_ALL_BANNER_ITEM",
        LOBBY_CHANGE_UI_TYPE: "CHANGE_LOBBY_UI_TYPE",
        LOBBY_OPEN_TOOLTIP: "LOBBY_OPEN_TOOLTIP",
        OPEN_MESSAGE_BOX: "OPEN_MESSAGE_BOX",
        OPEN_SLOT_ERROR_MESSAGE_BOX: "OPEN_SLOT_ERROR_MESSAGE_BOX",
        CLUB_ADD_CHAT_MESSAGE: "CLUB_ADD_CHAT_MESSAGE"
    };

    // ===================== 私有成员变量 =====================
    private _eventEmitter: cc.EventTarget = null!;

    // ===================== 核心方法 - 完全对齐原JS逻辑 =====================
    /** 获取事件名常量对象 */
    public getMSG(): typeof MessageRoutingManager.MSG {
        return MessageRoutingManager.MSG;
    }

    /** 初始化事件分发器 */
    public initMessageRoutingManager(): void {
        this._eventEmitter = new cc.EventTarget();
    }

    /** 添加事件监听 */
    public addListenerTarget(eventName: string, callback: Function, target: any): void {
        this._eventEmitter.on(eventName, callback, target);
    }

    /** 移除指定事件的指定监听 */
    public removeListenerTarget(eventName: string, callback: Function, target: any): void {
        this._eventEmitter.off(eventName, callback, target);
    }

    /** 移除某个目标节点的所有事件监听 */
    public removeListenerTargetAll(target: any): void {
        this._eventEmitter.targetOff(target);
    }

    /** 派发事件（核心方法） */
    public emitMessage(eventName: string, data: any = null): void {
        this._eventEmitter.emit(eventName, data);
    }
}